name: Code Coverage
on:
  pull_request:
    branches-ignore: [dependabot/**]
jobs:
  comment-coverage-difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - uses: actions/checkout@v3
      - name: yarn install for this PR
        run: yarn install # TODO: do we need --frozen-lockfile? we are yarn install-ing again below

      - name: Get coverage for this PR
        run: |
          go test -v -coverpkg=./... -coverprofile=profile.cov ./...
          echo "go-pr-cov=$(go tool cover -func profile.cov | grep total: | awk '{print substr($NF,1,length($NF)-1)}')" >> $GITHUB_ENV
          echo "ts-pr-cov=$(yarn test:coverage | grep 'All files' | awk '{print $10}')" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: main
      - name: yarn install for main
        run: yarn install

      - name: Get coverage on main # TODO: can consider if we should save this coverage as an artifact?
        run: |
          go test -v -coverpkg=./... -coverprofile=profile.cov ./...
          echo "go-main-cov=$(go tool cover -func profile.cov | grep total: | awk '{print substr($NF,1,length($NF)-1)}')" >> $GITHUB_ENV
          echo "ts-main-cov=$(yarn test:coverage | grep 'All files' | awk '{print $10}')" >> $GITHUB_ENV

      - name: Calculate coverage difference
        run: |
          echo "go-cov-difference=$(bc <<< '${{ env.go-pr-cov }} - ${{ env.go-main-cov }}')" >> $GITHUB_ENV
          echo "ts-cov-difference=$(bc <<< '${{ env.ts-pr-cov }} - ${{ env.ts-main-cov }}')" >> $GITHUB_ENV

      - name: Find previous comment, if any
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: |
            Code coverage report for PR #${{ github.event.pull_request.number }}
          # TODO: need unique string here -- any ideas or is this good enough?

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Code coverage report for PR #${{ github.event.pull_request.number }}

            |      |          Go                         | Typescript |
            |------| ----------------------------------- | ---------------- |
            | main | ${{ env.go-main-cov }}%             | ${{ env.ts-main-cov }}% |
            | PR   | ${{ env.go-pr-cov }}%               | ${{ env.ts-pr-cov }}%   |
            | difference | ${{ env.go-cov-difference }}% | ${{ env.ts-cov-difference }}% |
          edit-mode: replace
